### ISSUE TITLE
Error Code 998 while authenticating Aadhaar  by OTP

### ISSUE THREAD

**Issue by SatyaPavanKumar** [souvikdc9/aadhaarapi.net#12] opened 2018-01-31 10:34 UTC
I downloaded  project and started running by setting "Uidai.Aadhaar.Sample" as startup project.
All the data inside project is tested data by Uidai. I am trying to authenticate By OTP.

Kyc.KnowYourCustomerAsync().GetAwaiter().GetResult(); in program.cs file

**URL:** http://developer.uidai.gov.in/otp/1.6/public/9/9/MG41KIrkk5moCkcO8w-2fc01-P7I5S-6X2-X7luVcDgZyOa2LXs3ELI

**Body:**

<Otp tid="public" ac="public" sa="public" txn="20180131032427098" lk="MEaMX8fkRa6PqsqK6wGMrEXcXFl_oXHA-YuknI2uf0gKgZ80HaZgG3A" uid="999999990026" ver="1.6" ts="0001-01-01T00:00:00" xmlns="http://www.uidai.gov.in/authentication/otp/1.0">
  <Opts ch="01" xmlns="" />
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" />
      <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
      <Reference URI="">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
        <DigestValue>9Mv/mf6sByXfv3ZWxdnrDbenH+U=</DigestValue>
      </Reference>
    </SignedInfo>
    <SignatureValue>R5q3YHW8kUYCimSJPQMCZgNB+nDTINJtZ6Vog9sdmgBj8KoLzf3a8ebcWpeZrQAZ7rje3KRblDksxw+aXEFIFQ2jFq8IjzWgx58/BrRnZgh2kfoiv1Ve8hYYw2S+rQW5mKvbVs6aG18hSnbycYJE8Zgg5sbPak1faa8dRZBJhgqNfxvuYGEzPlTuYpA3v05jZeICvRX/eYg93iDIz0s1NJLiKiq/rI6mev8BY/eA7Pu6En7VUVnVcj47YStMiByZqUiuDQ6YrXZGd97kAC85H7gVRV7ZTkyDwulO/7ml6cEp9EpAReY6cvsw6ZzYMng1e1bTPj2CIboWKPHDlKqNSw==</SignatureValue>
    <KeyInfo>
      <X509Data>
        <X509SubjectName>CN=Public AUA for Staging Services, OU=Staging Services, O=Public AUA, L=Bangalore, S=KA, C=IN</X509SubjectName>
        <X509Certificate>MIIDuDCCAqCgAwIBAgIGA7J+eqryMA0GCSqGSIb3DQEBBQUAMIGNMQswCQYDVQQGEwJJTjELMAkGA1UECBMCS0ExEjAQBgNVBAcTCUJhbmdhbG9yZTETMBEGA1UEChMKUHVibGljIEFVQTEZMBcGA1UECxMQU3RhZ2luZyBTZXJ2aWNlczEtMCsGA1UEAxMkUm9vdCBQdWJsaWMgQVVBIGZvciBTdGFnaW5nIFNlcnZpY2VzMB4XDTE2MDUyNDE0NDAzMVoXDTIwMDUyNDE0NDAzMVowgYgxCzAJBgNVBAYTAklOMQswCQYDVQQIEwJLQTESMBAGA1UEBxMJQmFuZ2Fsb3JlMRMwEQYDVQQKEwpQdWJsaWMgQVVBMRkwFwYDVQQLExBTdGFnaW5nIFNlcnZpY2VzMSgwJgYDVQQDEx9QdWJsaWMgQVVBIGZvciBTdGFnaW5nIFNlcnZpY2VzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo4XxOsjK58Ud+tQd06Mk8Rd0qoyjA/3u+y0YVYEF6RgT8Ge1uVdTkIcVYaHyXuuHUPLLqGW1hPfVtn81UVIMGyrw5+t1c30wpGv3UJ6GCFu0sPGgG5NwkVbIUt2xgT/Or/kGzHjUJJy4Y6URSkZiDLDQQWRXvui5ZwwsYRJ8LhT0pSUwan1raG5Vl01GmlWVqsrCmnObuoYkN85iwG4/ERGshkgFCPak8B/jH3GPZSi1+FJLmCqMI1xxmTvf0kZb7ejm2IZFTo6ecYWJ1vylkzUI553RxVbnHCNZvFe3AyaKMyFlknFR0Fkl5+9Lpxz+VOajbCjicg7jIYCw76/xgQIDAQABoyEwHzAdBgNVHQ4EFgQUJHLir1/Tel8v/6OuIXpLS0JH8jIwDQYJKoZIhvcNAQEFBQADggEBAFE15qMGIlp8+M306FbhDEvo1vzxN2Pfvg/f92NXH59d2XZ/wuHxugL8qfcM5xkqsDeIRVxRdISpwiIWlqTitn6lenF85bvPQ09T/b09dVz/LxwU2Cm6+6H5/HZSoLtCKBOuRzAKQdxczpyfaqv9caFC+LegPQIm2HCwOM0A4KzhYcFhumGeyCbyVZsSQcJE7bYc/IHkR2erup7h5BACOZ/a+hHLPQok/uGvtEsR3roydNcNlR8Ja6Wc4eUf7kisTuZTxwRJI9DPVimbs0VAqhnsnVWAK3X4+6sFUq5WfHS4wTRhrR93JvEV5LlQ6UCXYOQMvTii8l07qxkDiysVsLQ=</X509Certificate>
      </X509Data>
    </KeyInfo>
  </Signature>
</Otp>

**Response:**

     <OtpRes txn="20180131032427098" err="998" actn="A202" 
   code="eb4619dba1734185b75763194f61128a" ts="2018-01-31T15:30:34.384+05:30" ret="n" 
   info="01{c039ac2f8cba7681dfa2470c9552173f11998bcf4cefc319419f8cf071e431ca,A,0001-01-
 01T00:00:00,1.6,20ef0f0c8d0eea98772412cea9b3b92612e3e53cb5e59152b5703165f56e8a53,efa1f375d7
 6194fa51a3556a97e641e61685f914d446979da50a551a4333ffd7,efa1f375d76194fa51a3556a97e641e616
  85f914d446979da50a551a4333ffd7,NA,NA}" />

What is exact issue am facing?

**Comment by himadrinath** [comment] 2018-01-31 14:44
@SatyaPavanKumar 

read this https://authportal.uidai.gov.in/web/uidai/developer

**Comment by ghost** [comment] 2018-02-01 03:13
Duplicate of #10

**Closed as completed by ghost** 2018-02-01 03:13 UTC
