### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by SatyaPavanKumar** [souvikdc9/aadhaarapi.net#11] opened 2018-01-31 09:01 UTC
I downloaded project right now and set "Uidai.Aadhaar.Sample" as start up project and debugged. I am facing below issue. Do i need to modify anything after i downloading. I did not modified any personal information which Uidai test data.

Auth.AuthenticateAsync().GetAwaiter().GetResult(); in program.cs which internally navigates to Auth cs file.

In Auth.cs file : 
// Perform Authentication
var apiClient = new AuthClient
{
AgencyInfo = Options.AgencyInfo,
Request = new AuthRequest(deviceContext) { Signer = Signer },
Response = new AuthResponse { Verifier = Verifier }
};
await apiClient.GetResponseAsync(); -- **Exception causing at this step.**

Pls. help me to solve this. Or am i need to change anything after downloading.
![503service](https://user-images.githubusercontent.com/32288442/35613906-54119ebe-0693-11e8-8081-4be187db0f91.png)

**Comment by ghost** [comment] 2018-02-01 03:12
Duplicate of #10

**Closed as completed by ghost** 2018-02-01 03:12 UTC
